version: '3'
services:
  web:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: symfonytest
      MYSQL_DATABASE: symfonytest
    volumes:
      - symfony-test-db:/var/lib/mysql
volumes:
  symfony-test-db: